# Generated by Django 4.2.1 on 2023-05-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=13)),
                ("published_date", models.DateField()),
                ("publisher", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("available_quantity", models.PositiveIntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
